
AZURE_OPENAI_ENDPOINT = redacted
AZURE_OPENAI_API_KEY = redacted
AZURE_DOCUMENT_INTELLIGENCE_ENDPOINT = redacted
AZURE_DOCUMENT_INTELLIGENCE_KEY = redacted
AZURE_STORAGE_ACCOUNT_NAME = redacted
AZURE_STORAGE_ACCOUNT_KEY = redacted
AZURE_STORAGE_CONTAINER_NAME = "Scientific_doc"
AZURE_AI_SEARCH_SERVICE_NAME = redacted
AZURE_AI_SEARCH_API_KEY = redacted
AZURE_AI_SEARCH_INDEX_NAME = "scientific-index"
